GeometryID:                       95     # GeometryID
############################
sipm_array_L:                     24.9         # mm - SiPM tile length (effective + dead space)
sipm_array_L_eff:                 23.9         # mm - SiPM effective tile length 
sipm_array_sizeZ:                 1.5          # mm - SiPM tile depth 
sipm_array_d:                     0.5          # mm - distance between two tiles
sipm_array_epoxy_layer_sizeZ:     0.4          # mm - thick resin layer depth
nx_tiles:                          5           # number of tiles' columns composing the plane
ny_tiles:                          2           # number of tiles' rows composing the plane
############################
nx_sipm_pixel:                    8            # number of pixels in a tile along X
ny_sipm_pixel:                    8            # number of pixels in a tile along Y
sipm_pixel_pitch_up:              0.27         # mm - distance between pixels (up)
sipm_pixel_pitch_down:            1.050        # mm - distance between pixels (down)
sipm_pixel_pitch_right:           0.27         # mm - distance between pixels (up)
sipm_pixel_pitch:                 3.1          # mm - pixel pitch
sipm_pixel_dead_up                0.65         # mm - pixel dead space (up)
sipm_array_substrate_sizeZ:       0.6          # mm - pixel substrate depth
sensitive_sipm_pixel_sizeX:       2.73         # mm - pixel sensitive length along X
sensitive_sipm_pixel_sizeY:       2.34         # mm - pixel sensitive length along Y
sensitive_sipm_pixel_sizeZ:       0.5          # mm - pixel sensitive length along Z
sipm_pixel_substrate_sizeZ:       0.29         # mm - pixel substrate depth
############################